export const FETCH_UNITS_REQUEST = 'FETCH_UNITS_REQUEST';
export const FETCH_UNITS_SUCCESS = 'FETCH_UNITS_SUCCESS';
export const FETCH_UNITS_FAILURE = 'FETCH_UNITS_FAILURE';

export const ADD_UNIT_REQUEST = 'ADD_UNIT_REQUEST';
export const ADD_UNIT_SUCCESS = 'ADD_UNIT_SUCCESS';
export const ADD_UNIT_FAILURE = 'ADD_UNIT_FAILURE';

export const REMOVE_UNIT_REQUEST = 'REMOVE_UNIT_REQUEST';
export const REMOVE_UNIT_SUCCESS = 'REMOVE_UNIT_SUCCESS';
export const REMOVE_UNIT_FAILURE = 'REMOVE_UNIT_FAILURE';

